FROM amazoncorretto:17-alpine

WORKDIR /app

ARG JAR_FILE=./build/libs/hollang-1.0.0.jar

COPY ${JAR_FILE} hollang-prod.jar

ENV PROFILES prod

EXPOSE 80

ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/hollang-prod.jar"]
