version: "3.8"
services:
  database:
    container_name: hollang-database-local
    image: "mysql"
    restart: always
    volumes:
      - hollang-database-local-data:/var/lib/mysql
    env_file:
      - ./env/local/mysql.env
    ports:
      - "3306:3306"

volumes:
  hollang-database-local-data: