version: "3.8"
services:
  database:
    container_name: hollang-database-local
    image: "mysql"
    restart: always
    volumes:
      - hollang-database-local-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: hollang_local
    ports:
      - "3306:3306"

volumes:
  hollang-database-local-data: