FROM amazoncorretto:17-alpine

WORKDIR /app

ARG JAR_FILE=./build/libs/hollang-1.0.0.jar

COPY ${JAR_FILE} hollang-dev.jar

ENV PROFILES dev

EXPOSE 80

ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/hollang-dev.jar"]
