spring:
  config:
    activate:
      on-profile: prod, dev, local, test
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always